# AI Support Ticket Analyzer - Exploracion y limpieza inicial


Este notebook documenta la primera etapa del proyecto: cargar el dataset, diagnosticar problemas de calidad y tomar decisiones iniciales de limpieza antes de construir la API, el enriquecimiento con IA y el dashboard.

## 1. Importacion de librerias

In [1]:
import pandas as pd

## 2. Carga del dataset


Se carga el archivo `tickets.csv` y se visualizan las primeras filas para entender la estructura general de los datos.

In [2]:
df = pd.read_csv("tickets.csv")
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,822,James Johnston,MARIE76@EXAMPLE.COM,29,Female,Lenovo ThinkPad,2021-07-19,Cancellation request,Hardware issue,I'm having an issue with the Lenovo ThinkPad. ...,Closed,Critical,Social media,2023-06-01 14:57:35,2023-06-01 16:42:35,3.0
1,526,Cody Bailey,lori66@example.com,30,Male,Microsoft Office,19 de diciembre 2020,Refund request,Product setup,I'm having an issue with the Microsoft Office....,Closed,medium,Chat,2023-06-01 21:44:43,2023-06-01 07:55:43,1.0
2,2046,Aaron Nelson,jcrawford@example.net,41,Male,Amazon Kindle,2020-04-26,product inquiry,Software bug,I'm having an issue with the Amazon Kindle. Pl...,Open,High,Social media,NaN,NaN,NaN
3,1161,Jonathan Webb,gwhite@example.com,46,Male,Nikon D,2020-06-05,Cancellation request,Software bug,The Nikon D is unable to establish a stable in...,Pending Customer Response,Medium,Chat,2023-06-01 18:44:19,NaN,NaN
4,7542,Rebecca Collins,williamscharles@example.com,42,Male,Google Pixel,10-23-2020,Product inquiry,Refund request,I'm having an issue with the Google Pixel. Ple...,Closed,Medium,Email,2023-06-01 08:44:55,2023-06-01 16:07:55,1.0

## 3. Diagnostico inicial


Antes de limpiar, se revisan dimensiones, tipos de datos, valores faltantes y duplicados. Esto permite diferenciar problemas reales de datos frente a valores ausentes esperados por el proceso de soporte.

In [3]:
df.shape

(409, 16)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     409 non-null    int64
 1   Customer Name                 409 non-null    object
 2   Customer Email                389 non-null    object
 3   Customer Age                  386 non-null    object
 4   Customer Gender               409 non-null    object
 5   Product Purchased             409 non-null    object
 6   Date of Purchase              378 non-null    object
 7   Ticket Type                   409 non-null    object
 8   Ticket Subject                409 non-null    object
 9   Ticket Description            409 non-null    object
 10  Ticket Status                 409 non-null    object
 11  Ticket Priority               395 non-null    object
 12  Ticket Channel                409 non-null    object
 13  First Response Time           268 non-null    object
 14  Time to Resolution            146 non-null    object
 15  Customer Satisfaction Rating  146 non-null    float64
dtypes: float64(1), int64(1), object(14)
memory usage: 51.3+ KB

In [5]:
df.isna().sum()

Ticket ID                         0
Customer Name                     0
Customer Email                   20
Customer Age                     23
Customer Gender                   0
Product Purchased                 0
Date of Purchase                 31
Ticket Type                       0
Ticket Subject                    0
Ticket Description                0
Ticket Status                     0
Ticket Priority                  14
Ticket Channel                    0
First Response Time             141
Time to Resolution              263
Customer Satisfaction Rating    263
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(6)

## 4. Revision y tratamiento de duplicados


Primero se visualizan los registros duplicados, incluyendo tanto el original como su copia, para confirmar que se trata de duplicados exactos.

In [7]:
df[df.duplicated(keep=False)].sort_values("Ticket ID")

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
1,526,Cody Bailey,lori66@example.com,30,Male,Microsoft Office,19 de diciembre 2020,Refund request,Product setup,I'm having an issue with the Microsoft Office....,Closed,medium,Chat,2023-06-01 21:44:43,2023-06-01 07:55:43,1.0
199,526,Cody Bailey,lori66@example.com,30,Male,Microsoft Office,19 de diciembre 2020,Refund request,Product setup,I'm having an issue with the Microsoft Office....,Closed,medium,Chat,2023-06-01 21:44:43,2023-06-01 07:55:43,1.0
5,2288,Kylie Hardy,tsimpson@example.com,27,Male,Amazon Kindle,2020-10-22,Product inquiry,Payment issue,I'm having an issue with the Amazon Kindle. Pl...,Pending Customer Response,Medium,Chat,2023-06-01 21:53:30,NaN,NaN
365,2288,Kylie Hardy,tsimpson@example.com,27,Male,Amazon Kindle,2020-10-22,Product inquiry,Payment issue,I'm having an issue with the Amazon Kindle. Pl...,Pending Customer Response,Medium,Chat,2023-06-01 21:53:30,NaN,NaN
320,2928,Bradley Graham,NaN,69,Female,iPhone,20/09/2021,Refund request,Hardware issue,I'm having an issue with the iPhone. Please as...,Closed,Low,Phone,2023-06-01 05:42:00,2023-06-01 01:50:00,2.0
402,2928,Bradley Graham,NaN,69,Female,iPhone,20/09/2021,Refund request,Hardware issue,I'm having an issue with the iPhone. Please as...,Closed,Low,Phone,2023-06-01 05:42:00,2023-06-01 01:50:00,2.0
340,4862,JuliÃ¡ Terry,qsmith@example.net,65,Female,NIKON D,2020-12-22,Billing Inquiry,Account access,I'm having an issue with the Nikon D. Please a...,Pending Customer Response,baja,Social media,2023-06-01 23:10:15,NaN,NaN
33,4862,JuliÃ¡ Terry,qsmith@example.net,65,Female,NIKON D,2020-12-22,Billing Inquiry,Account access,I'm having an issue with the Nikon D. Please a...,Pending Customer Response,baja,Social media,2023-06-01 23:10:15,NaN,NaN
84,4916,Jennifer Vargas,jacobpatrick@example.net,66,Female,Fitbit Versa Smartwatch,03/10/2021,Billing inquiry,Software bug,I'm having an issue with the Fitbit Versa Smar...,Closed,Critical,Chat,2023-06-01 19:13:30,2023-06-01 03:08:30,4.0
135,4916,Jennifer Vargas,jacobpatrick@example.net,66,Female,Fitbit Versa Smartwatch,03/10/2021,Billing inquiry,Software bug,I'm having an issue with the Fitbit Versa Smar...,Closed,Critical,Chat,2023-06-01 19:13:30,2023-06-01 03:08:30,4.0
252,6202,Susan Bennett,elizabethandersen@example.com,43,Female,Roomba Robot Vacuum,2021-07-16,refund,Payment issue,I'm having an issue with the Roomba Robot Vacu...,Closed,urgent,Social media,2023-06-01 09:48:01,2023-06-01 01:26:01,5.0
22,6202,Susan Bennett,elizabethandersen@example.com,43,Female,Roomba Robot Vacuum,2021-07-16,refund,Payment issue,I'm having an issue with the Roomba Robot Vacu...,Closed,urgent,Social media,2023-06-01 09:48:01,2023-06-01 01:26:01,5.0

Se encontraron **6 registros duplicados exactos**. Se eliminan para evitar que afecten metricas como el volumen total de tickets, la distribucion por prioridad y los conteos por producto.

In [8]:
df = df.drop_duplicates().reset_index(drop=True)

Despues de eliminar duplicados, se revisan nuevamente las primeras filas del dataset limpio.

In [9]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,822,James Johnston,MARIE76@EXAMPLE.COM,29,Female,Lenovo ThinkPad,2021-07-19,Cancellation request,Hardware issue,I'm having an issue with the Lenovo ThinkPad. ...,Closed,Critical,Social media,2023-06-01 14:57:35,2023-06-01 16:42:35,3.0
1,526,Cody Bailey,lori66@example.com,30,Male,Microsoft Office,19 de diciembre 2020,Refund request,Product setup,I'm having an issue with the Microsoft Office....,Closed,medium,Chat,2023-06-01 21:44:43,2023-06-01 07:55:43,1.0
2,2046,Aaron Nelson,jcrawford@example.net,41,Male,Amazon Kindle,2020-04-26,product inquiry,Software bug,I'm having an issue with the Amazon Kindle. Pl...,Open,High,Social media,NaN,NaN,NaN
3,1161,Jonathan Webb,gwhite@example.com,46,Male,Nikon D,2020-06-05,Cancellation request,Software bug,The Nikon D is unable to establish a stable in...,Pending Customer Response,Medium,Chat,2023-06-01 18:44:19,NaN,NaN
4,7542,Rebecca Collins,williamscharles@example.com,42,Male,Google Pixel,10-23-2020,Product inquiry,Refund request,I'm having an issue with the Google Pixel. Ple...,Closed,Medium,Email,2023-06-01 08:44:55,2023-06-01 16:07:55,1.0

## 5. Analisis de valores nulos segun estado del ticket


Se revisa si los nulos en satisfaccion y tiempo de resolucion corresponden a tickets que aun no han sido cerrados. Esta distincion es clave: no todo valor nulo debe imputarse o eliminarse.

In [10]:
df[df["Customer Satisfaction Rating"].isna()]["Ticket Status"].value_counts()

Ticket Status
Open                         141
Pending Customer Response    120
Name: count, dtype: int64

In [11]:
df[df["Time to Resolution"].isna()]["Ticket Status"].value_counts()

Ticket Status
Open                         141
Pending Customer Response    120
Name: count, dtype: int64

In [12]:
df[df["Ticket Status"] == "Closed"][["Time to Resolution", "Customer Satisfaction Rating"]].isna().sum()

Time to Resolution              0
Customer Satisfaction Rating    0
dtype: int64

Los valores nulos no se tratan todos de la misma forma. En campos como `Time to Resolution` y `Customer Satisfaction Rating`, los nulos parecen estar relacionados con el estado del ticket: normalmente un ticket abierto o pendiente no tiene resolucion ni calificacion.


En cambio, nulos en `Customer Email`, `Customer Age`, `Date of Purchase` y `Ticket Priority` si se consideran problemas de calidad de datos que requieren normalizacion o manejo especial. `Ticket Priority` es especialmente importante porque impacta directamente las metricas de priorizacion.

## 6. Observaciones y riesgos pendientes


- `Customer Age` venia como tipo `object` porque mezcla numeros validos, valores fuera de rango y texto. Se creo una columna limpia para conservar el dato original.

- `Date of Purchase` tiene formatos mixtos, por ejemplo fechas ISO, fechas con texto en espanol y formatos con `/` o `-`.

- Algunas fechas de `Time to Resolution` parecen anteriores a `First Response Time` en registros cerrados. Esto debe marcarse como inconsistencia temporal.

- `Ticket Priority` tiene nulos y valores escritos en formatos distintos. Este campo debe normalizarse antes de calcular KPIs por prioridad.

In [13]:
df["Customer Age"].value_counts()

Customer Age
48             13
41             12
54             11
47             10
69             10
55             10
52              9
21              9
62              9
46              9
42              9
24              9
28              9
43              8
33              8
32              8
200             8
26              8
66              8
60              8
25              7
70              7
49              7
18              7
65              7
31              7
45              7
34              6
29              6
0               6
36              6
22              6
50              6
999             6
57              6
30              6
20              6
59              6
68              5
53              5
64              5
35              5
23              5
51              5
27              4
-3              4
37              4
thirty          4
63              4
38              4
44              4
veinticinco     3
19              3
56              3
40              3
39              3
61              3
67              2
58              2
Name: count, dtype: int64

In [14]:
age_mapping = {
    "thirty": 30,
    "veinticinco": 25
}
df["clean_customer_age"] = (
    df["Customer Age"]
    .replace(age_mapping)
    .pipe(pd.to_numeric, errors="coerce")
)

In [15]:
df["clean_customer_age"].value_counts().sort_values()

clean_customer_age
 67.0      2
 58.0      2
 19.0      3
 39.0      3
 40.0      3
 56.0      3
 61.0      3
 27.0      4
 38.0      4
 37.0      4
 63.0      4
-3.0       4
 44.0      4
 53.0      5
 35.0      5
 68.0      5
 23.0      5
 64.0      5
 51.0      5
 999.0     6
 50.0      6
 29.0      6
 57.0      6
 0.0       6
 34.0      6
 36.0      6
 20.0      6
 22.0      6
 59.0      6
 70.0      7
 65.0      7
 31.0      7
 49.0      7
 18.0      7
 45.0      7
 66.0      8
 32.0      8
 43.0      8
 60.0      8
 26.0      8
 200.0     8
 33.0      8
 46.0      9
 28.0      9
 52.0      9
 62.0      9
 42.0      9
 24.0      9
 21.0      9
 25.0     10
 69.0     10
 30.0     10
 47.0     10
 55.0     10
 54.0     11
 41.0     12
 48.0     13
Name: count, dtype: int64

In [16]:
df.loc[
    ~df["clean_customer_age"].between(18, 90),
    "clean_customer_age"
] = pd.NA

In [17]:
df["clean_customer_age"].value_counts().sort_values()

clean_customer_age
67.0     2
58.0     2
56.0     3
61.0     3
39.0     3
19.0     3
40.0     3
37.0     4
44.0     4
38.0     4
27.0     4
63.0     4
64.0     5
35.0     5
68.0     5
53.0     5
51.0     5
23.0     5
20.0     6
34.0     6
29.0     6
59.0     6
50.0     6
57.0     6
22.0     6
36.0     6
49.0     7
18.0     7
65.0     7
70.0     7
31.0     7
45.0     7
60.0     8
32.0     8
66.0     8
43.0     8
33.0     8
26.0     8
46.0     9
42.0     9
62.0     9
28.0     9
52.0     9
24.0     9
21.0     9
69.0    10
55.0    10
47.0    10
30.0    10
25.0    10
54.0    11
41.0    12
48.0    13
Name: count, dtype: int64

In [18]:
df["clean_customer_age"].isna().sum()

np.int64(47)

## 8. Normalizacion de `Ticket Priority`


`Ticket Priority` es una columna clave para el dashboard, porque alimenta indicadores como tickets de prioridad alta o critica. Primero se revisan los valores originales para identificar diferencias por mayusculas, espacios, idiomas, abreviaturas y codigos.

In [19]:
df["Ticket Priority"].value_counts(dropna=False)

Ticket Priority
Critical      60
Medium        53
High          53
Low           53
NaN           14
P3            11
Low           11
urgent        10
 Medium       10
baja          10
4              9
P1             9
med            9
1              8
3              8
medium         8
P4             8
High           8
HIGH           8
 Critical      7
CRITICAL       7
alta           7
P2             6
2              6
high           4
low            4
critical       2
Name: count, dtype: int64

El primer conteo muestra categorias duplicadas por formato: mayusculas/minusculas, espacios al inicio o final, abreviaturas (`med`) y codigos (`P1`, `P2`, etc.). Antes de hacer un mapeo de negocio, se aplica una normalizacion textual basica.

In [20]:
df["Ticket Priority"] = df["Ticket Priority"].str.strip().str.lower()

Despues de aplicar `strip()` y `lower()`, las categorias se reducen. Esto corrige problemas de formato, pero todavia falta decidir como agrupar semanticamente valores equivalentes.

In [21]:
df["Ticket Priority"].value_counts(dropna=False)

Ticket Priority
critical    76
high        73
medium      71
low         68
NaN         14
p3          11
urgent      10
baja        10
med          9
4            9
p1           9
p4           8
3            8
1            8
alta         7
2            6
p2           6
Name: count, dtype: int64

### Decision sobre codigos y valores ambiguos


Los valores `P1`, `P2`, `P3` y `P4` se interpretan como una escala de prioridad donde `P1` es la mas critica. En cambio, los valores numericos aislados (`1`, `2`, `3`, `4`) son ambiguos: podrian representar una escala ascendente o descendente. Se buscó observar los comentarios manualmente , se nota una tendencia a fallas funcionales de dispositivos en prioridad 1, pero tambien se encuentran este tipo de obervaciones para tickets con prioridad 4 


Por esa razon, los numeros aislados no se mapean automaticamente. Se conservan como `Unknown` en `clean_ticket_priority` para evitar introducir una suposicion no verificable. Mas adelante, el LLM podra generar una columna separada (`ai_suggested_priority`) basada en el contenido del ticket.

In [22]:
priority_mapping = {
    "critical": "Critical",
    "urgent": "Critical",
    "p1": "Critical",

    "high": "High",
    "alta": "High",
    "p2": "High",

    "medium": "Medium",
    "med": "Medium",
    "p3": "Medium",

    "low": "Low",
    "baja": "Low",
    "p4": "Low",
}
df["clean_ticket_priority"] = (
    df["Ticket Priority"]
    .map(priority_mapping)
    .fillna("Unknown")
)

Con el mapeo anterior se crea `clean_ticket_priority`, una version limpia de prioridad que conserva como `Unknown` los nulos y los valores ambiguos. Esta columna sera la base para KPIs y filtros del dashboard.

In [23]:
(df["clean_ticket_priority"].value_counts(dropna=False)*100)/403

clean_ticket_priority
Critical    23.573201
Medium      22.580645
High        21.339950
Low         21.339950
Unknown     11.166253
Name: count, dtype: float64

La distribucion porcentual se calcula sobre **403 tickets**, que corresponde al dataset despues de eliminar los 6 duplicados exactos. El resultado muestra que aproximadamente 11% de los registros quedan como `Unknown`, principalmente por nulos o prioridades ambiguas.

## 9. Conversion de tiempos de soporte


Las columnas `First Response Time` y `Time to Resolution` contienen fecha y hora. Se convierten a tipo `datetime` conservando horas, minutos y segundos para permitir validaciones temporales y futuras metricas de operacion.


`First Response Time` se interpreta como el primer contacto del equipo de soporte con el cliente despues de recibir el ticket. `Time to Resolution` representa el momento en que el caso fue resuelto.

In [25]:
df[["First Response Time","Time to Resolution"]]

     First Response Time   Time to Resolution
0    2023-06-01 14:57:35  2023-06-01 16:42:35
1    2023-06-01 21:44:43  2023-06-01 07:55:43
2                    NaN                  NaN
3    2023-06-01 18:44:19                  NaN
4    2023-06-01 08:44:55  2023-06-01 16:07:55
..                   ...                  ...
398  2023-06-01 00:53:33                  NaN
399                  NaN                  NaN
400  2023-06-01 04:03:16  2023-06-01 03:09:16
401  2023-06-01 19:04:02  2023-06-01 11:41:02
402  2023-06-01 11:44:33                  NaN

[403 rows x 2 columns]

Se usa un formato explicito (`%Y-%m-%d %H:%M:%S`) porque estas dos columnas parecen seguir una estructura consistente. `errors="coerce"` permite convertir valores invalidos o vacios en `NaT`, sin detener la ejecucion.

In [26]:
datetime_format = "%Y-%m-%d %H:%M:%S"

df["clean_first_response_time"] = pd.to_datetime(
    df["First Response Time"],
    format=datetime_format,
    errors="coerce"
)

df["clean_time_to_resolution"] = pd.to_datetime(
    df["Time to Resolution"],
    format=datetime_format,
    errors="coerce"
)

In [28]:
df[["First Response Time","Time to Resolution"]]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     403 non-null    int64
 1   Customer Name                 403 non-null    object
 2   Customer Email                384 non-null    object
 3   Customer Age                  380 non-null    object
 4   Customer Gender               403 non-null    object
 5   Product Purchased             403 non-null    object
 6   Date of Purchase              372 non-null    object
 7   Ticket Type                   403 non-null    object
 8   Ticket Subject                403 non-null    object
 9   Ticket Description            403 non-null    object
 10  Ticket Status                 403 non-null    object
 11  Ticket Priority               389 non-null    object
 12  Ticket Channel                403 non-null    object
 13  First Response Time           262 non-null    object
 14  Time to Resolution            142 non-null    object
 15  Customer Satisfaction Rating  142 non-null    float64
 16  clean_customer_age            356 non-null    float64
 17  clean_ticket_priority         403 non-null    object
 18  clean_first_response_time     262 non-null    datetime64[ns]
 19  clean_time_to_resolution      142 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(15)
memory usage: 63.1+ KB

La validacion con `df.info()` confirma que las columnas limpias quedaron como `datetime64[ns]`. Los nulos restantes son esperados en tickets abiertos o pendientes, porque aun pueden no tener primera respuesta o resolucion.

### Validacion de consistencia temporal


Bajo un flujo esperado de soporte, `First Response Time` deberia ocurrir antes de `Time to Resolution`. Sin embargo, los casos donde la resolucion aparece antes de la primera respuesta no se corrigen automaticamente.


Estos registros pueden representar errores de datos, diferencias de zona horaria, problemas de exportacion o un flujo operativo irregular donde el equipo resolvio el caso antes de comunicar formalmente la primera respuesta al cliente.

In [30]:
invalid_resolution_time = df[
    df["clean_first_response_time"].notna()
    & df["clean_time_to_resolution"].notna()
    & (df["clean_time_to_resolution"] < df["clean_first_response_time"])
]

invalid_resolution_time[
    [
        "Ticket ID",
        "Ticket Status",
        "First Response Time",
        "Time to Resolution",
        "clean_first_response_time",
        "clean_time_to_resolution"
    ]
]
invalid_resolution_time.shape[0]

68

Se detectaron **68 registros** donde `Time to Resolution` es anterior a `First Response Time`. Por ahora se documentan como casos que requieren revision, en lugar de modificar las fechas manualmente.

## 10. Limpieza de `Date of Purchase`


Esta columna tiene formatos mixtos: `YYYY-MM-DD`, `MM-DD-YYYY`, `DD/MM/YYYY` y fechas con meses en espanol. Por eso primero se inspeccionan valores y luego se construye una conversion personalizada.

In [40]:
df["Date of Purchase"].value_counts().head(35)

Date of Purchase
2021-12-19              3
2020-11-11              2
05-16-2020              2
2020-03-31              2
09/02/2021              2
28 de abril 2021        2
03-24-2021              2
2021-12-13              2
2021-02-18              2
2021-03-30              2
02-27-2021              2
2021-09-30              2
2020-09-03              2
16/08/2021              2
2020-12-04              2
2021-08-15              2
17/06/2020              2
11-12-2020              2
2020-05-10              2
24 de noviembre 2020    2
2020-02-11              2
2020-02-18              2
06-09-2020              2
2020-09-17              2
2020-07-25              2
2020-03-17              2
2021-11-27              2
22/03/2021              2
09/02/2020              2
28/04/2021              2
2020-07-22              1
10 de enero 2021        1
18/01/2021              1
2020-03-06              1
03-16-2021              1
Name: count, dtype: int64

In [42]:
df["Date of Purchase"].dropna().sample(20)

104              25/10/2021
146              2021-07-11
324              04/10/2021
140              09/08/2020
81               05-29-2020
59               2021-03-25
370              09/02/2020
243              03-25-2020
349              02-27-2021
391      21 de octubre 2020
308              11-19-2020
27               25/12/2021
315              09/02/2020
401              27/11/2021
188    24 de noviembre 2021
383              03-16-2021
238              05-16-2020
196        7 de agosto 2020
366              14/02/2020
242              2021-09-07
Name: Date of Purchase, dtype: object

In [47]:
df["Date of Purchase"].isna().sum()

np.int64(31)

Se intenta una conversion inicial con `pd.to_datetime` para medir el problema. El aumento de nulos permite identificar que muchos valores no faltaban originalmente, sino que fallaron por formato.

In [44]:
df["clean_date_of_purchase"] = pd.to_datetime(
    df["Date of Purchase"],
    errors="coerce")

In [46]:
df["clean_date_of_purchase"].isna().sum()

np.int64(232)

In [50]:
conversion_failed_purchase_date = df[
    df["Date of Purchase"].notna()
    & df["clean_date_of_purchase"].isna()
]
conversion_failed_purchase_date["Date of Purchase"].value_counts()

Date of Purchase
28/04/2021              2
11-12-2020              2
05-16-2020              2
28 de abril 2021        2
17/06/2020              2
                       ..
08-07-2020              1
03/03/2020              1
20 de diciembre 2020    1
19/04/2021              1
27/11/2021              1
Name: count, Length: 188, dtype: int64

Para manejar fechas en espanol, se normalizan los nombres de meses a ingles y se elimina el conector `de`. Esto convierte valores como `19 de diciembre 2020` en `19 december 2020`.

In [51]:
spanish_months = {
    "enero": "january",
    "febrero": "february",
    "marzo": "march",
    "abril": "april",
    "mayo": "may",
    "junio": "june",
    "julio": "july",
    "agosto": "august",
    "septiembre": "september",
    "setiembre": "september",
    "octubre": "october",
    "noviembre": "november",
    "diciembre": "december",
}
def normalize_spanish_date_text(value):
    if pd.isna(value):
        return value

    text = str(value).strip().lower()

    for spanish_month, english_month in spanish_months.items():
        text = text.replace(spanish_month, english_month)

    text = text.replace(" de ", " ")

    return text

In [52]:
df["purchase_date_text_normalized"] = df["Date of Purchase"].apply(
    normalize_spanish_date_text
)

In [53]:
df[["Date of Purchase", "purchase_date_text_normalized"]].head(20)

        Date of Purchase purchase_date_text_normalized
0             2021-07-19                    2021-07-19
1   19 de diciembre 2020              19 december 2020
2             2020-04-26                    2020-04-26
3             2020-06-05                    2020-06-05
4             10-23-2020                    10-23-2020
5             2020-10-22                    2020-10-22
6        20 de mayo 2021                   20 may 2021
7             28/04/2021                    28/04/2021
8             2021-03-15                    2021-03-15
9             2021-07-31                    2021-07-31
10            2021-11-21                    2021-11-21
11            2020-07-31                    2020-07-31
12            30/10/2020                    30/10/2020
13            2021-09-16                    2021-09-16
14            2020-11-17                    2020-11-17
15            22/07/2020                    22/07/2020
16            05-13-2021                    05-13-2021
17            06/12/2021                    06/12/2021
18            06/07/2021                    06/07/2021
19     5 de octubre 2021                5 october 2021

In [54]:
df["clean_date_of_purchase"] = pd.to_datetime(
    df["purchase_date_text_normalized"],
    errors="coerce"
)

La funcion `parse_purchase_date` intenta varios formatos explicitamente. Esto evita depender de una inferencia automatica de pandas, que no funciona bien cuando la misma columna mezcla formatos.

In [57]:
def parse_purchase_date(value):
    if pd.isna(value):
        return pd.NaT

    normalized = normalize_spanish_date_text(value)

    formats = [
        "%Y-%m-%d",      # 2021-07-19
        "%m-%d-%Y",      # 10-23-2020
        "%d/%m/%Y",      # 28/04/2021
        "%d %B %Y",      # 19 december 2020
    ]

    for date_format in formats:
        parsed = pd.to_datetime(
            normalized,
            format=date_format,
            errors="coerce"
        )

        if pd.notna(parsed):
            return parsed

    return pd.NaT

In [58]:
df["clean_date_of_purchase"] = df["Date of Purchase"].apply(parse_purchase_date)

In [59]:
df[["Date of Purchase", "purchase_date_text_normalized", "clean_date_of_purchase"]].head(20)

        Date of Purchase purchase_date_text_normalized clean_date_of_purchase
0             2021-07-19                    2021-07-19             2021-07-19
1   19 de diciembre 2020              19 december 2020             2020-12-19
2             2020-04-26                    2020-04-26             2020-04-26
3             2020-06-05                    2020-06-05             2020-06-05
4             10-23-2020                    10-23-2020             2020-10-23
5             2020-10-22                    2020-10-22             2020-10-22
6        20 de mayo 2021                   20 may 2021             2021-05-20
7             28/04/2021                    28/04/2021             2021-04-28
8             2021-03-15                    2021-03-15             2021-03-15
9             2021-07-31                    2021-07-31             2021-07-31
10            2021-11-21                    2021-11-21             2021-11-21
11            2020-07-31                    2020-07-31             2020-07-31
12            30/10/2020                    30/10/2020             2020-10-30
13            2021-09-16                    2021-09-16             2021-09-16
14            2020-11-17                    2020-11-17             2020-11-17
15            22/07/2020                    22/07/2020             2020-07-22
16            05-13-2021                    05-13-2021             2021-05-13
17            06/12/2021                    06/12/2021             2021-12-06
18            06/07/2021                    06/07/2021             2021-07-06
19     5 de octubre 2021                5 october 2021             2021-10-05

La validacion final confirma que `clean_date_of_purchase` conserva solo los 31 nulos originales. No quedaron fechas no nulas sin convertir.

In [60]:
df["clean_date_of_purchase"].isna().sum()

np.int64(31)

In [61]:
df[
    df["Date of Purchase"].notna()
    & df["clean_date_of_purchase"].isna()
]["Date of Purchase"].value_counts()

Series([], Name: count, dtype: int64)

## 11. Normalizacion de `Ticket Type`


Se normaliza `Ticket Type` para agrupar variantes equivalentes como `billing` y `billing inquiry`, o `refund` y `refund request`. Esta columna sera usada para filtros, metricas y categorizacion.

In [63]:
df["Ticket Type"].value_counts(dropna=False)

Ticket Type
Product inquiry         60
Billing inquiry         57
Technical issue         49
Refund request          48
Cancellation request    46
billing                 14
product_inquiry         12
 product inquiry        11
cancel request          11
refund                  11
Cancellation Request     9
 technical issue         9
Product Inquiry          9
Refund Request           8
technical_issue          8
refund_request           8
cancellation_request     7
Technical Issue          7
 Billing inquiry         6
Billing Inquiry          5
TECHNICAL ISSUE          5
billing_inquiry          3
Name: count, dtype: int64

In [64]:
df["ticket_type_text"] = df["Ticket Type"].str.strip().str.lower().str.replace("_", " ")

In [65]:
df["ticket_type_text"].value_counts(dropna=False)

ticket_type_text
product inquiry         92
technical issue         78
billing inquiry         71
refund request          64
cancellation request    62
billing                 14
cancel request          11
refund                  11
Name: count, dtype: int64

Se revisan ejemplos de categorias cercanas antes de aplicar el mapeo, para confirmar que las equivalencias sean razonables.

In [66]:
df[df["ticket_type_text"] == "refund"]

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,First Response Time,Time to Resolution,Customer Satisfaction Rating,clean_customer_age,clean_ticket_priority,clean_first_response_time,clean_time_to_resolution,clean_date_of_purchase,purchase_date_text_normalized,ticket_type_text
22,6202,Susan Bennett,elizabethandersen@example.com,43,Female,Roomba Robot Vacuum,2021-07-16,refund,Payment issue,I'm having an issue with the Roomba Robot Vacu...,...,2023-06-01 09:48:01,2023-06-01 01:26:01,5.0,43.0,Critical,2023-06-01 09:48:01,2023-06-01 01:26:01,2021-07-16,2021-07-16,refund
23,3007,Christina Miller,charlotteschneider@example.net,NaN,Other,Bose QuietComfort,08-31-2020,refund,Product setup,I'm having an issue with the Bose QuietComfort...,...,NaN,NaN,NaN,NaN,Medium,NaT,NaT,2020-08-31,08-31-2020,refund
96,7954,Andre Wagner Jr.,robertdavis@example.com,42,Female,Bose SoundLink Speaker,24/01/2020,refund,Account access,I'm facing a problem with my Bose SoundLink Sp...,...,2023-06-01 09:53:23,2023-06-01 03:23:23,4.0,42.0,Unknown,2023-06-01 09:53:23,2023-06-01 03:23:23,2020-01-24,24/01/2020,refund
105,6597,Emily Welch,qmann@example.net,31,Male,iPhone,NaN,refund,Account access,I'm having an issue with the iPhone. Please as...,...,NaN,NaN,NaN,31.0,Medium,NaT,NaT,NaT,NaN,refund
192,7120,Taylor Johnson,ericapadilla@example.com,62,Female,GoPro Action Camera,12-15-2021,refund,Product compatibility,I'm having an issue with the GoPro Action Came...,...,NaN,NaN,NaN,62.0,Critical,NaT,NaT,2021-12-15,12-15-2021,refund
203,8006,Robert Small,joshuabaldwin@example.net,24,Female,Fitbit Charge,05-06-2021,refund,Product compatibility,I'm having an issue with the Fitbit Charge. Pl...,...,NaN,NaN,NaN,24.0,Medium,NaT,NaT,2021-05-06,05-06-2021,refund
299,7008,Robert Brewer,zachary61@example.net,26,Other,Samsung Soundbar,2020-09-22,refund,Data loss,I've noticed a software bug in the Samsung Sou...,...,NaN,NaN,NaN,26.0,Critical,NaT,NaT,2020-09-22,2020-09-22,refund
315,1777,David Bray,woodjustin@example.com,31,Male,Nikon D,09/02/2020,refund,Account access,I'm having an issue with the Nikon D. Please a...,...,2023-06-01 08:01:21,NaN,NaN,31.0,Unknown,2023-06-01 08:01:21,NaT,2020-02-09,09/02/2020,refund
323,1965,John Martin,BOYDJEFFERY@EXAMPLE.ORG,42,Female,Adobe Photoshop,NaN,refund,Cancellation request,I'm having an issue with the Adobe Photoshop. ...,...,2023-06-01 20:47:49,NaN,NaN,42.0,Unknown,2023-06-01 20:47:49,NaT,NaT,NaN,refund
339,591,Mark Woodward,dawn75@example.com,39,Male,Google Pixel,NaN,refund,Refund request,I'm having an issue with the Google Pixel. Ple...,...,2023-06-01 20:40:17,NaN,NaN,39.0,Low,2023-06-01 20:40:17,NaT,NaT,NaN,refund
382,10,WilliÃ¡m Dawson,clopez@example.com,27,Male,Dyson Vacuum Cleaner,2020-03-06,refund,Payment issue,My Dyson Vacuum Cleaner is making strange nois...,...,2023-06-01 09:25:48,NaN,NaN,27.0,Critical,2023-06-01 09:25:48,NaT,2020-03-06,2020-03-06,refund

In [67]:
df[df["ticket_type_text"] == "refund request"]

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,First Response Time,Time to Resolution,Customer Satisfaction Rating,clean_customer_age,clean_ticket_priority,clean_first_response_time,clean_time_to_resolution,clean_date_of_purchase,purchase_date_text_normalized,ticket_type_text
1,526,Cody Bailey,lori66@example.com,30,Male,Microsoft Office,19 de diciembre 2020,Refund request,Product setup,I'm having an issue with the Microsoft Office....,...,2023-06-01 21:44:43,2023-06-01 07:55:43,1.0,30.0,Medium,2023-06-01 21:44:43,2023-06-01 07:55:43,2020-12-19,19 december 2020,refund request
10,7974,Oscar Miller,JERRYHOBBS@EXAMPLE.COM,54,Other,Autodesk AutoCAD,2021-11-21,Refund Request,Cancellation request,I'm having an issue with the Autodesk AutoCAD....,...,NaN,NaN,NaN,54.0,High,NaT,NaT,2021-11-21,2021-11-21,refund request
12,4273,MELISSA EDWARDS,brianbutler@example.com,66,Female,CANON DSLR CAMERA,30/10/2020,Refund request,Battery life,The Canon DSLR Camera is unable to establish a...,...,NaN,NaN,NaN,66.0,High,NaT,NaT,2020-10-30,30/10/2020,refund request
14,7429,Mrs. Makayla Richards,raymondgarcia@example.com,52,Male,Amazon Kindle,2020-11-17,Refund Request,Account access,"My Amazon Kindle crashed, and I lost all the d...",...,2023-06-01 17:15:18,2023-06-01 05:28:18,5.0,52.0,Critical,2023-06-01 17:15:18,2023-06-01 05:28:18,2020-11-17,2020-11-17,refund request
18,320,Jamie Green,qbaker@example.net,29,Female,Nest Thermostat,06/07/2021,Refund request,Hardware issue,I've encountered a data loss issue with my Nes...,...,NaN,NaN,NaN,29.0,Critical,NaT,NaT,2021-07-06,06/07/2021,refund request
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,7887,Justin Brown,kfoster@example.net,33,Male,LG OLED,2020-06-09,Refund request,Product compatibility,I'm having an issue with the LG OLED. Please a...,...,2023-06-01 19:50:55,NaN,NaN,33.0,Unknown,2023-06-01 19:50:55,NaT,2020-06-09,2020-06-09,refund request
385,6268,Kristy Fernandez,hparker@example.com,thirty,Male,GoPro Hero,05-22-2020,Refund request,Payment issue,I'm having an issue with the GoPro Hero. Pleas...,...,2023-06-01 18:06:33,2023-06-01 05:26:33,3.0,30.0,Low,2023-06-01 18:06:33,2023-06-01 05:26:33,2020-05-22,05-22-2020,refund request
396,6571,Tara Guzman,ggarcia@example.org,37,Male,iPhone,2020-07-05,Refund request,Product compatibility,I'm having trouble connecting my iPhone to my ...,...,2023-06-01 01:18:27,2023-06-01 07:35:27,5.0,37.0,High,2023-06-01 01:18:27,2023-06-01 07:35:27,2020-07-05,2020-07-05,refund request
397,5001,Mariah Price,paulray@example.com,45,Other,Sony 4K HDR TV,08-07-2020,refund_request,Account access,I'm facing a problem with my Sony 4K HDR TV. T...,...,NaN,NaN,NaN,45.0,Critical,NaT,NaT,2020-08-07,08-07-2020,refund request
400,7042,Joanna Hoover,trichardson@example.net,52,Male,Bose QuietComfort,19/04/2021,Refund request,Refund request,I'm having an issue with the Bose QuietComfort...,...,2023-06-01 04:03:16,2023-06-01 03:09:16,3.0,52.0,Low,2023-06-01 04:03:16,2023-06-01 03:09:16,2021-04-19,19/04/2021,refund request

El mapeo crea `clean_ticket_type`, una version consistente de la categoria del ticket. A diferencia de la prioridad numerica, aqui las equivalencias son claras y no ambiguas.

In [68]:
ticket_type_mapping = {
    "product inquiry": "Product Inquiry",
    "technical issue": "Technical Issue",
    "billing inquiry": "Billing Inquiry",
    "billing": "Billing Inquiry",
    "refund request": "Refund Request",
    "refund": "Refund Request",
    "cancellation request": "Cancellation Request",
    "cancel request": "Cancellation Request",
}

df["clean_ticket_type"] = (
    df["ticket_type_text"]
    .map(ticket_type_mapping)
    .fillna("Unknown")
)

In [70]:
df["clean_ticket_type"].value_counts(dropna=False)

clean_ticket_type
Product Inquiry         92
Billing Inquiry         85
Technical Issue         78
Refund Request          75
Cancellation Request    73
Name: count, dtype: int64

## 12. Limpieza de campos de texto simples


Se limpian campos de texto usados para busqueda, filtros y agrupaciones. En emails se normalizan espacios y mayusculas. En productos se normaliza el formato de escritura.

In [72]:
df["clean_customer_email"] = (
    df["Customer Email"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [78]:
df["product_text"] = (
    df["Product Purchased"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.title()
)

### Validacion de categorias restantes


Se revisan `Ticket Status`, `Ticket Channel` y `Customer Gender`. Como ya se observan consistentes, solo se crean columnas limpias con `strip()` para mantener el flujo de limpieza uniforme.

In [ ]:
df["Ticket Status"].value_counts(dropna=False)

Ticket Status
Closed                       142
Open                         141
Pending Customer Response    120
Name: count, dtype: int64

In [81]:
df["Ticket Channel"].value_counts(dropna=False)

Ticket Channel
Social media    104
Phone           102
Email           100
Chat             97
Name: count, dtype: int64

In [82]:
df["Customer Gender"].value_counts(dropna=False)

Customer Gender
Female    140
Male      139
Other     124
Name: count, dtype: int64

In [ ]:
df["clean_ticket_channel"] = df["Ticket Channel"].astype("string").str.strip()

0      Social media
1              Chat
2      Social media
3              Chat
4             Email
           ...
398           Email
399           Email
400           Email
401           Phone
402            Chat
Name: clean_ticket_channel, Length: 403, dtype: string

In [85]:
df["clean_ticket_channel"].value_counts(dropna = False)

clean_ticket_channel
Social media    104
Phone           102
Email           100
Chat             97
Name: count, dtype: Int64

In [93]:
df.head(0)

Empty DataFrame
Columns: [Ticket ID, Customer Name, Customer Email, Customer Age, Customer Gender, Product Purchased, Date of Purchase, Ticket Type, Ticket Subject, Ticket Description, Ticket Status, Ticket Priority, Ticket Channel, First Response Time, Time to Resolution, Customer Satisfaction Rating, clean_customer_age, clean_ticket_priority, clean_first_response_time, clean_time_to_resolution, clean_date_of_purchase, purchase_date_text_normalized, ticket_type_text, clean_ticket_type, clean_customer_email, product_text, clean_ticket_channel]
Index: []

[0 rows x 27 columns]

## 13. Metricas base


Con las columnas limpias se calculan metricas iniciales para el dashboard y el futuro endpoint `/summary`: total de tickets, tickets abiertos, prioridades altas/criticas y distribuciones por canal, estado y prioridad.

Una metrica interesante es el tiempo entre primera respuesta y resolucion. Como el dataset no incluye fecha de creacion del ticket, no es posible calcular el tiempo total desde la apertura hasta la resolucion.

In [ ]:
total_tickets = len(df)

open_tickets = (df["Ticket Status"] == "Open").sum()

high_critical_tickets = df["clean_ticket_priority"].isin(
    ["High", "Critical"]).sum()

In [91]:
print(f"Numero total de tickets creados:{total_tickets}, Numero de tickets abiertos:{open_tickets},Numero de tickets criticos y altos:{high_critical_tickets}")

Numero total de tickets creados:403, Numero de tickets abiertos:141,Numero de tickets criticos y altos:181

### Tiempo entre primera respuesta y resolucion


Se explora la diferencia entre `clean_time_to_resolution` y `clean_first_response_time`. Como ya se detectaron inconsistencias temporales, esta metrica debe interpretarse con cuidado y no deberia usarse como KPI final sin filtrar registros invalidos.

In [95]:
time = df["clean_time_to_resolution"] - df["clean_first_response_time"]

In [105]:
deltafirstresponseresolved = ((time.dt.total_seconds() / 3600).mean())*60

In [108]:
print(f"El tiempo promedio entre la resolucion y la primera interaccion es de {deltafirstresponseresolved} minutos ")

El tiempo promedio entre la resolucion y la primera interaccion es de -42.11971830985915 minutos

La presencia de valores negativos o promedios poco intuitivos puede indicar errores de datos o flujos operativos donde el caso fue resuelto antes de registrar una primera respuesta formal al cliente.

Este promedio indica que primeramente se estan resolviendo los tickets antes de dar la primera repsuesta al customer , se recomienda revisar la metodologia , con el fin de

In [114]:
df["clean_ticket_channel"].value_counts(dropna = False)

clean_ticket_channel
Social media    104
Phone           102
Email           100
Chat             97
Name: count, dtype: Int64

In [109]:
df["clean_ticket_priority"].value_counts()

clean_ticket_priority
Critical    95
Medium      91
High        86
Low         86
Unknown     45
Name: count, dtype: int64

In [115]:
df["Ticket Status"].value_counts()

Ticket Status
Closed                       142
Open                         141
Pending Customer Response    120
Name: count, dtype: int64

## Estado actual


Completado:

- Carga, diagnostico inicial y eliminacion de duplicados.

- Analisis de nulos esperados y problematicos.

- Limpieza de `Customer Age`, `Ticket Priority`, fechas, `Ticket Type`, email y producto.

- Creacion de metricas base para dashboard/API.


Siguiente paso:

- Crear enriquecimiento mock de IA: categoria, prioridad sugerida, resumen, sentimiento y equipo responsable.

## 14. Enriquecimiento mock de IA

In [116]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,clean_ticket_priority,clean_first_response_time,clean_time_to_resolution,clean_date_of_purchase,purchase_date_text_normalized,ticket_type_text,clean_ticket_type,clean_customer_email,product_text,clean_ticket_channel
0,822,James Johnston,MARIE76@EXAMPLE.COM,29,Female,Lenovo ThinkPad,2021-07-19,Cancellation request,Hardware issue,I'm having an issue with the Lenovo ThinkPad. ...,...,Critical,2023-06-01 14:57:35,2023-06-01 16:42:35,2021-07-19,2021-07-19,cancellation request,Cancellation Request,marie76@example.com,Lenovo Thinkpad,Social media
1,526,Cody Bailey,lori66@example.com,30,Male,Microsoft Office,19 de diciembre 2020,Refund request,Product setup,I'm having an issue with the Microsoft Office....,...,Medium,2023-06-01 21:44:43,2023-06-01 07:55:43,2020-12-19,19 december 2020,refund request,Refund Request,lori66@example.com,Microsoft Office,Chat
2,2046,Aaron Nelson,jcrawford@example.net,41,Male,Amazon Kindle,2020-04-26,product inquiry,Software bug,I'm having an issue with the Amazon Kindle. Pl...,...,High,NaT,NaT,2020-04-26,2020-04-26,product inquiry,Product Inquiry,jcrawford@example.net,Amazon Kindle,Social media
3,1161,Jonathan Webb,gwhite@example.com,46,Male,Nikon D,2020-06-05,Cancellation request,Software bug,The Nikon D is unable to establish a stable in...,...,Medium,2023-06-01 18:44:19,NaT,2020-06-05,2020-06-05,cancellation request,Cancellation Request,gwhite@example.com,Nikon D,Chat
4,7542,Rebecca Collins,williamscharles@example.com,42,Male,Google Pixel,10-23-2020,Product inquiry,Refund request,I'm having an issue with the Google Pixel. Ple...,...,Medium,2023-06-01 08:44:55,2023-06-01 16:07:55,2020-10-23,10-23-2020,product inquiry,Product Inquiry,williamscharles@example.com,Google Pixel,Email

In [117]:
def assign_responsible_team(ticket_type):
    mapping = {
        "Technical Issue": "Technical Support",
        "Billing Inquiry": "Billing",
        "Refund Request": "Billing",
        "Cancellation Request": "Customer Success",
        "Product Inquiry": "Customer Support",
    }
    return mapping.get(ticket_type, "General Support")
def detect_sentiment(text):
    text = str(text).lower()

    urgent_words = ["urgent", "critical", "immediately", "as soon as"]
    negative_words = ["issue", "problem", "error", "unable", "can't", "bug", "failed"]

    if any(word in text for word in urgent_words):
        return "Urgent"
    if any(word in text for word in negative_words):
        return "Frustrated"

    return "Neutral"
def suggest_priority(row):
    text = f"{row['Ticket Subject']} {row['Ticket Description']}".lower()

    if row["clean_ticket_priority"] != "Unknown":
        return row["clean_ticket_priority"]

    if any(word in text for word in ["urgent", "critical", "unable", "not working", "failed"]):
        return "High"

    if any(word in text for word in ["refund", "payment", "billing", "cancel"]):
        return "Medium"

    return "Low"
def create_mock_summary(row):
    return (
        f"Cliente reporta {row['clean_ticket_type'].lower()} "
        f"relacionado con {row['product_text']}. "
        f"Asunto: {row['Ticket Subject']}."
    )

In [118]:
df["ai_category"] = df["clean_ticket_type"]

df["ai_suggested_priority"] = df.apply(suggest_priority, axis=1)

df["ai_summary"] = df.apply(create_mock_summary, axis=1)

df["ai_sentiment"] = df["Ticket Description"].apply(detect_sentiment)

df["ai_responsible_team"] = df["clean_ticket_type"].apply(assign_responsible_team)

In [123]:
df[["clean_ticket_priority", "ai_suggested_priority"]].value_counts()

clean_ticket_priority  ai_suggested_priority
Critical               Critical                 95
Medium                 Medium                   91
High                   High                     86
Low                    Low                      86
Unknown                Low                      32
                       High                      7
                       Medium                    6
Name: count, dtype: int64

In [125]:
df["ai_sentiment"].value_counts()
df["ai_responsible_team"].value_counts()

ai_responsible_team
Billing              160
Customer Support      92
Technical Support     78
Customer Success      73
Name: count, dtype: int64

La mayor carga sugerida recae en Billing, principalmente por tickets de facturación y reembolsos. Customer Success también tiene un volumen relevante, cercano a Technical Support, lo que sugiere una cantidad importante de solicitudes de cancelación y posibles riesgos de retención.